site_name: Hector Input Catalogues

site_author: Sam Vaughan

repo_url: https://github.com/samvaughan/hector-input-catalogues
repo_name: Hector Input Catalogues

nav:
  - Home: 'index.md'
  - Running the Code: 'walkthrough.md'
  - Adding a New Region: 'adding_a_new_region.md'
  - Other Hector Documentation: 
    - Home: https://samvaughan.info/hector
    - Observing Pipeline: 'https://samvaughan.info/hector-observing/'
    - Tiling : 'https://samvaughan.info/hector-tiling/'
    - Database: 'https://samvaughan.info/hector-database/'

theme: 
  name: material
  palette:
    primary: black
  logo: img/favicon.png
  favicon: img/favicon.png
  features:
    - content.footnote.tooltips

  
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js