site_name: Hector Input Catalogues

site_author: Sam Vaughan

repo_url: https://github.com/samvaughan/hector-input-catalogues
repo_name: Hector Input Catalogues

nav:
  - Home: 'index.md'

theme: 
  name: material
  palette:
    primary: black
  logo: img/favicon.png
  favicon: img/favicon.png

  
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js