snakemake --cores 1 -- results/Tiling/HectorClusters_including_fg/A0085/A0085_tiling_complete.flag
snakemake --cores 1 -- results/Tiling/HectorClusters_including_fg/A0119/A0119_tiling_complete.flag
snakemake --cores 1 -- results/Tiling/HectorClusters_including_fg/A0151/A0151_tiling_complete.flag
snakemake --cores 1 -- results/Tiling/HectorClusters_including_fg/A2399/A2399_tiling_complete.flag
snakemake --cores 1 -- results/Tiling/HectorClusters_including_fg/A3158/A3158_tiling_complete.flag
snakemake --cores 1 -- results/Tiling/HectorClusters_including_fg/A3266/A3266_tiling_complete.flag
snakemake --cores 1 -- results/Tiling/HectorClusters_including_fg/A3376/A3376_tiling_complete.flag
snakemake --cores 1 -- results/Tiling/HectorClusters_including_fg/A3391_A3395/A3391_A3395_tiling_complete.flag
snakemake --cores 1 -- results/Tiling/HectorClusters_including_fg/A3667/A3667_tiling_complete.flag
snakemake --cores 1 -- results/Tiling/HectorClusters_including_fg/A3716/A3716_tiling_complete.flag
