# This is an example configuration file to the full Hector Survey simulator.

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Target selection options

# This is the master catalogue
input_master_catalogue_filename: results/FinalInputCatalogues/HectorClusters_final_input.parquet

BoundaryType: /Users/samvaughan/Science/Hector/HectorObservationPipeline/SelectionFunctions/custom_selection_function.yaml
zlimit: 0.1
MstarMin: 8
MstarMax: 12
SparseFunction: 1
MSparseCut1: 10.0
minRe: 1.5

# Name of the input source catalogue - mainly for plotting
SourceCat: "HectorClusters"

# This is the selection we do on the pandas table
selection: (table.iloc[:,23]>0) & (table.iloc[:,7]>0) & (table.iloc[:,68]>0)

# Here we say which columns in the master catalogue correspond to which variables the survey simulator expects. Use None (no quotes) if they don't exist
Columns:
  CATID: 1
  RA: 3
  DEC: 4
  Re: 23
  z: 7
  Mstar: 68
  GAL_MAG_U: 58
  GAL_MAG_G: 8
  GAL_MAG_R: 9
  GAL_MAG_I: 66
  GAL_MAG_Z: 10
  GAL_MU_E_U: None
  GAL_MU_0_U: None
  GAL_MU_E_G: None
  GAL_MU_0_G: None
  GAL_MU_E_R: None
  GAL_MU_0_R: None
  GAL_MU_E_I: None
  GAL_MU_0_I: None
  GAL_MU_E_Z: None
  GAL_MU_0_Z: None
  Ellipticity_r: 69
  SersicIndex_r: None
  MassHIpred: None
  WALLABYflag: None
  Dingoflag: None

total_area: 0

output_folder: results/TargetSelectedMasterCatalogues/HectorClusters
# Stem to attach to all the tile files we'll make. Will have an underscore after it
output_filename_stem: HectorClusters

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Tiling options

fresh_start: True
MAX_TRIES: 999
configure_field: True

tiling_type: greedy
allocation_type: random
proximity: 220 # This is  14.5*15.008
Nsel: 19
N_targets_per_Hector_field: 19
Nsel_guides: 100
Nsel_standards: 100

TwoDF_FOV_radius: 1.0
exclusion_zone: 220 # This is 14.5mm in arcseconds: 14.5 * 15.008
Hector_FOV_outer_radius: 0.9318
Hector_FOV_inner_radius: 0.0

fraction_to_reobserve: 0.0

#Do we want to use the 'hybrid' approach to rescale the proximity value if the configuration code is struggling?
Rescale_proximity: True

fill_spares_with_repeats: True

columns_for_target_tile_saving:
  [
    "ID",
    "RA",
    "DEC",
    "g_mag",
    "r_mag",
    "i_mag",
    "z_mag",
    "y_mag",
    "GAIA_g_mag",
    "GAIA_bp_mag",
    "GAIA_rp_mag",
    "Mstar",
    "Re",
    "z",
    "GAL_MU_E_R",
    "pmRA",
    "pmDEC",
  ]

columns_for_guide_tile_saving:
  ["ID", "RA", "DEC", "r_mag", "type", "pmRA", "pmDEC"]
